CREATE TABLE [Valid].[LearningDelivery] (
    [UKPRN]              INT          NOT NULL,
    [LearnRefNumber]     VARCHAR (12) NOT NULL,
    [LearnAimRef]        VARCHAR (8)  NOT NULL,
    [AimType]            INT          NOT NULL,
    [AimSeqNumber]       INT          NOT NULL,
    [LearnStartDate]     DATE         NOT NULL,
    [OrigLearnStartDate] DATE         NULL,
    [LearnPlanEndDate]   DATE         NOT NULL,
    [FundModel]          INT          NOT NULL,
    [ProgType]           INT          NULL,
    [FworkCode]          INT          NULL,
    [PwayCode]           INT          NULL,
    [StdCode]            BIGINT       NULL,
    [PartnerUKPRN]       INT          NULL,
    [DelLocPostCode]     VARCHAR (8)  NULL,
    [AddHours]           INT          NULL,
    [PriorLearnFundAdj]  INT          NULL,
    [OtherFundAdj]       INT          NULL,
    [ConRefNumber]       VARCHAR (20) NULL,
    [EmpOutcome]         INT          NULL,
    [CompStatus]         INT          NULL,
    [LearnActEndDate]    DATE         NULL,
    [WithdrawReason]     INT          NULL,
    [Outcome]            INT          NULL,
    [AchDate]            DATE         NULL,
    [OutGrade]           VARCHAR (6)  NULL,
    [SWSupAimId]         VARCHAR (36) NULL,
    [LrnDelFAM_ADL]      VARCHAR (5)  NULL,
    [LrnDelFAM_ASL]      VARCHAR (5)  NULL,
    [LrnDelFAM_EEF]      VARCHAR (5)  NULL,
    [LrnDelFAM_FFI]      VARCHAR (5)  NULL,
    [LrnDelFAM_FLN]      VARCHAR (5)  NULL,
    [LrnDelFAM_HEM1]     VARCHAR (5)  NULL,
    [LrnDelFAM_HEM2]     VARCHAR (5)  NULL,
    [LrnDelFAM_HEM3]     VARCHAR (5)  NULL,
    [LrnDelFAM_HHS1]     VARCHAR (5)  NULL,
    [LrnDelFAM_HHS2]     VARCHAR (5)  NULL,
    [LrnDelFAM_LDM1]     VARCHAR (5)  NULL,
    [LrnDelFAM_LDM2]     VARCHAR (5)  NULL,
    [LrnDelFAM_LDM3]     VARCHAR (5)  NULL,
    [LrnDelFAM_LDM4]     VARCHAR (5)  NULL,
    [LrnDelFAM_NSA]      VARCHAR (5)  NULL,
    [LrnDelFAM_POD]      VARCHAR (5)  NULL,
    [LrnDelFAM_RES]      VARCHAR (5)  NULL,
    [LrnDelFAM_SOF]      VARCHAR (5)  NULL,
    [LrnDelFAM_SPP]      VARCHAR (5)  NULL,
    [LrnDelFAM_WPP]      VARCHAR (5)  NULL,
    [ProvSpecMon_A]      VARCHAR (20) NULL,
    [ProvSpecMon_B]      VARCHAR (20) NULL,
    [ProvSpecMon_C]      VARCHAR (20) NULL,
    [ProvSpecMon_D]      VARCHAR (20) NULL,
    PRIMARY KEY CLUSTERED ([UKPRN] ASC, [LearnRefNumber] ASC, [AimSeqNumber] ASC)
);

