CREATE TABLE [Valid].[Learner] (
    [UKPRN]              INT           NOT NULL,
    [LearnRefNumber]     VARCHAR (12)  NOT NULL,
    [PrevLearnRefNumber] VARCHAR (12)  NULL,
    [PrevUKPRN]          INT           NULL,
    [ULN]                BIGINT        NOT NULL,
    [FamilyName]         VARCHAR (100) NULL,
    [GivenNames]         VARCHAR (100) NULL,
    [DateOfBirth]        DATE          NULL,
    [Ethnicity]          INT           NOT NULL,
    [Sex]                VARCHAR (1)   NOT NULL,
    [LLDDHealthProb]     INT           NOT NULL,
    [NINumber]           VARCHAR (9)   NULL,
    [PriorAttain]        INT           NULL,
    [Accom]              INT           NULL,
    [ALSCost]            INT           NULL,
    [PlanLearnHours]     INT           NULL,
    [PlanEEPHours]       INT           NULL,
    [MathGrade]          VARCHAR (4)   NULL,
    [EngGrade]           VARCHAR (4)   NULL,
    [HomePostcode]       VARCHAR (8)   NULL,
    [CurrentPostcode]    VARCHAR (8)   NULL,
    [LrnFAM_DLA]         INT           NULL,
    [LrnFAM_ECF]         INT           NULL,
    [LrnFAM_EDF1]        INT           NULL,
    [LrnFAM_EDF2]        INT           NULL,
    [LrnFAM_EHC]         INT           NULL,
    [LrnFAM_FME]         INT           NULL,
    [LrnFAM_HNS]         INT           NULL,
    [LrnFAM_LDA]         INT           NULL,
    [LrnFAM_LSR1]        INT           NULL,
    [LrnFAM_LSR2]        INT           NULL,
    [LrnFAM_LSR3]        INT           NULL,
    [LrnFAM_LSR4]        INT           NULL,
    [LrnFAM_MCF]         INT           NULL,
    [LrnFAM_NLM1]        INT           NULL,
    [LrnFAM_NLM2]        INT           NULL,
    [LrnFAM_PPE1]        INT           NULL,
    [LrnFAM_PPE2]        INT           NULL,
    [LrnFAM_SEN]         INT           NULL,
    [ProvSpecMon_A]      VARCHAR (20)  NULL,
    [ProvSpecMon_B]      VARCHAR (20)  NULL,
    PRIMARY KEY CLUSTERED ([UKPRN] ASC, [LearnRefNumber] ASC)
);

