CREATE TABLE [Rulebase].[AEC_LearningDelivery_Period] (
    [UKPRN]                                        INT             NOT NULL,
    [LearnRefNumber]                               VARCHAR (12)    NOT NULL,
    [AimSeqNumber]                                 INT             NOT NULL,
    [Period]                                       INT             NOT NULL,
    [DisadvFirstPayment]                           DECIMAL (10, 5) NULL,
    [DisadvSecondPayment]                          DECIMAL (10, 5) NULL,
    [FundLineType]                                 VARCHAR (60)    NULL,
    [InstPerPeriod]                                INT             NULL,
    [LDApplic1618FrameworkUpliftBalancingPayment]  DECIMAL (10, 5) NULL,
    [LDApplic1618FrameworkUpliftCompletionPayment] DECIMAL (10, 5) NULL,
    [LDApplic1618FrameworkUpliftOnProgPayment]     DECIMAL (10, 5) NULL,
    [LearnDelContType]                             VARCHAR (50)    NULL,
    [LearnDelFirstEmp1618Pay]                      DECIMAL (10, 5) NULL,
    [LearnDelFirstProv1618Pay]                     DECIMAL (10, 5) NULL,
    [LearnDelLevyNonPayInd]                        INT             NULL,
    [LearnDelSecondEmp1618Pay]                     DECIMAL (10, 5) NULL,
    [LearnDelSecondProv1618Pay]                    DECIMAL (10, 5) NULL,
    [LearnDelSFAContribPct]                        DECIMAL (10, 5) NULL,
    [LearnSuppFund]                                BIT             NULL,
    [LearnSuppFundCash]                            DECIMAL (10, 5) NULL,
    [MathEngBalPayment]                            DECIMAL (10, 5) NULL,
    [MathEngBalPct]                                DECIMAL (8, 5)  NULL,
    [MathEngOnProgPayment]                         DECIMAL (10, 5) NULL,
    [MathEngOnProgPct]                             DECIMAL (8, 5)  NULL,
    [ProgrammeAimBalPayment]                       DECIMAL (10, 5) NULL,
    [ProgrammeAimCompletionPayment]                DECIMAL (10, 5) NULL,
    [ProgrammeAimOnProgPayment]                    DECIMAL (10, 5) NULL,
    PRIMARY KEY CLUSTERED ([UKPRN] ASC, [LearnRefNumber] ASC, [AimSeqNumber] ASC, [Period] ASC)
);

