CREATE TABLE [Rulebase].[AEC_ApprenticeshipPriceEpisode] (
    [UKPRN]                                            INT             NOT NULL,
    [LearnRefNumber]                                   VARCHAR (12)    NOT NULL,
    [PriceEpisodeIdentifier]                           VARCHAR (25)    NOT NULL,
    [EpisodeEffectiveTNPStartDate]                     DATE            NULL,
    [EpisodeStartDate]                                 DATE            NULL,
    [PriceEpisodeActualEndDate]                        DATE            NULL,
    [PriceEpisodeActualInstalments]                    INT             NULL,
    [PriceEpisodeAimSeqNumber]                         INT             NULL,
    [PriceEpisodeCappedRemainingTNPAmount]             DECIMAL (10, 5) NULL,
    [PriceEpisodeCompleted]                            BIT             NULL,
    [PriceEpisodeCompletionElement]                    DECIMAL (10, 5) NULL,
    [PriceEpisodeExpectedTotalMonthlyValue]            DECIMAL (10, 5) NULL,
    [PriceEpisodeFirstAdditionalPaymentThresholdDate]  DATE            NULL,
    [PriceEpisodeInstalmentValue]                      DECIMAL (10, 5) NULL,
    [PriceEpisodePlannedEndDate]                       DATE            NULL,
    [PriceEpisodePlannedInstalments]                   INT             NULL,
    [PriceEpisodePreviousEarnings]                     DECIMAL (10, 5) NULL,
    [PriceEpisodeRemainingAmountWithinUpperLimit]      DECIMAL (10, 5) NULL,
    [PriceEpisodeRemainingTNPAmount]                   DECIMAL (10, 5) NULL,
    [PriceEpisodeSecondAdditionalPaymentThresholdDate] DATE            NULL,
    [PriceEpisodeTotalEarnings]                        DECIMAL (10, 5) NULL,
    [PriceEpisodeTotalTNPPrice]                        DECIMAL (10, 5) NULL,
    [PriceEpisodeUpperBandLimit]                       DECIMAL (10, 5) NULL,
    [PriceEpisodeUpperLimitAdjustment]                 DECIMAL (10, 5) NULL,
    [TNP1]                                             DECIMAL (10, 5) NULL,
    [TNP2]                                             DECIMAL (10, 5) NULL,
    [TNP3]                                             DECIMAL (10, 5) NULL,
    [TNP4]                                             DECIMAL (10, 5) NULL,
    [PriceEpisodeContractType]                         VARCHAR (50)    NULL,
    [PriceEpisodeFundLineType]                         VARCHAR (60)    NULL,
    [PriceEpisodePreviousEarningsSameProvider]         DECIMAL (10, 5) NULL,
    PRIMARY KEY CLUSTERED ([UKPRN] ASC, [LearnRefNumber] ASC, [PriceEpisodeIdentifier] ASC)
);

