CREATE TABLE [Rulebase].[AEC_LearningDelivery] (
    [UKPRN]                                         INT             NOT NULL,
    [LearnRefNumber]                                VARCHAR (12)    NOT NULL,
    [AimSeqNumber]                                  INT             NOT NULL,
    [ActualDaysIL]                                  INT             NULL,
    [ActualNumInstalm]                              INT             NULL,
    [AdjStartDate]                                  DATE            NULL,
    [AgeAtProgStart]                                INT             NULL,
    [AppAdjLearnStartDate]                          DATE            NULL,
    [ApplicCompDate]                                DATE            NULL,
    [CombinedAdjProp]                               DECIMAL (10, 5) NULL,
    [Completed]                                     BIT             NULL,
    [DisUpFactAdj]                                  DECIMAL (10, 4) NULL,
    [FirstIncentiveThresholdDate]                   DATE            NULL,
    [FundStart]                                     BIT             NULL,
    [LDApplic1618FrameworkUpliftBalancingValue]     DECIMAL (10, 5) NULL,
    [LDApplic1618FrameworkUpliftCompElement]        DECIMAL (10, 5) NULL,
    [LDApplic1618FRameworkUpliftCompletionValue]    DECIMAL (10, 5) NULL,
    [LDApplic1618FrameworkUpliftMonthInstalVal]     DECIMAL (10, 5) NULL,
    [LDApplic1618FrameworkUpliftPrevEarnings]       DECIMAL (10, 5) NULL,
    [LDApplic1618FrameworkUpliftRemainingAmount]    DECIMAL (10, 5) NULL,
    [LDApplic1618FrameworkUpliftTotalActEarnings]   DECIMAL (10, 5) NULL,
    [LearnAimRef]                                   VARCHAR (8)     NULL,
    [LearnDel1618AtStart]                           BIT             NULL,
    [LearnDelAppAccDaysIL]                          INT             NULL,
    [LearnDelApplicDisadvAmount]                    DECIMAL (10, 5) NULL,
    [LearnDelApplicEmp1618Incentive]                DECIMAL (10, 5) NULL,
    [LearnDelApplicEmpDate]                         DATE            NULL,
    [LearnDelApplicProv1618FrameworkUplift]         DECIMAL (10, 5) NULL,
    [LearnDelApplicProv1618Incentive]               DECIMAL (10, 5) NULL,
    [LearnDelApplicTot1618Incentive]                DECIMAL (10, 5) NULL,
    [LearnDelAppPrevAccDaysIL]                      INT             NULL,
    [LearnDelDaysIL]                                INT             NULL,
    [LearnDelDisadAmount]                           DECIMAL (10, 5) NULL,
    [LearnDelEligDisadvPayment]                     BIT             NULL,
    [LearnDelHistDaysThisApp]                       INT             NULL,
    [LearnDelInitialFundLineType]                   VARCHAR (60)    NULL,
    [LearnDelSEMContWaiver]                         BIT             NULL,
    [MathEngAimValue]                               DECIMAL (10, 5) NULL,
    [OutstandNumOnProgInstalm]                      INT             NULL,
    [PlannedNumOnProgInstalm]                       INT             NULL,
    [PlannedTotalDaysIL]                            INT             NULL,
    [SecondIncentiveThresholdDate]                  DATE            NULL,
    [ThresholdDays]                                 INT             NULL,
    [AppAdjLearnStartDateMatchPathway]              DATE            NULL,
    [LearnDelHistProgEarnings]                      DECIMAL (10, 5) NULL,
    [LDApplic1618FrameworkUpliftPrevEarningsStage1] DECIMAL (10, 5) NULL,
    [LearnDelEmpIdFirstAdditionalPaymentThreshold]  INT             NULL,
    [LearnDelEmpIdSecondAdditionalPaymentThreshold] INT             NULL,
    PRIMARY KEY CLUSTERED ([UKPRN] ASC, [LearnRefNumber] ASC, [AimSeqNumber] ASC)
);

