CREATE TABLE [Rulebase].[TBL_LearningDelivery] (
    [UKPRN]                             INT             NOT NULL,
    [LearnRefNumber]                    VARCHAR (12)    NOT NULL,
    [AimSeqNumber]                      INT             NOT NULL,
    [AchApplicDate]                     DATE            NULL,
    [AchEligible]                       BIT             NULL,
    [Achieved]                          BIT             NULL,
    [AchievementApplicVal]              DECIMAL (10, 5) NULL,
    [ActualDaysIL]                      INT             NULL,
    [ActualNumInstalm]                  INT             NULL,
    [AdjProgStartDate]                  DATE            NULL,
    [AdjStartDate]                      DATE            NULL,
    [AgeStandardStart]                  INT             NULL,
    [ApplicFundValDate]                 DATE            NULL,
    [CombinedAdjProp]                   DECIMAL (10, 5) NULL,
    [CoreGovContCapApplicVal]           DECIMAL (10, 5) NULL,
    [EmpIdAchDate]                      INT             NULL,
    [EmpIdFirstDayStandard]             INT             NULL,
    [EmpIdFirstYoungAppDate]            INT             NULL,
    [EmpIdSecondYoungAppDate]           INT             NULL,
    [EmpIdSmallBusDate]                 INT             NULL,
    [FundLine]                          VARCHAR (50)    NULL,
    [LDLnrRedDate]                      DATE            NULL,
    [LDRedundancyCashMonths]            INT             NULL,
    [LDRedundancyCashRemainingCapped]   DECIMAL (7, 2)  NULL,
    [LDRedundancyCashRemainingUncapped] DECIMAL (7, 2)  NULL,
    [LDRedundancyCashStartDate]         DATE            NULL,
    [LearnAimRef]                       VARCHAR (8)     NULL,
    [LearnDelDaysIL]                    INT             NULL,
    [LearnDelStandardAccDaysIL]         INT             NULL,
    [LearnDelStandardPrevAccDaysIL]     INT             NULL,
    [LearnDelStandardTotalDaysIL]       INT             NULL,
    [MathEngAimValue]                   DECIMAL (10, 5) NULL,
    [MathEngLSFFundStart]               BIT             NULL,
    [MathEngLSFThresholdDays]           INT             NULL,
    [OutstandNumOnProgInstalm]          INT             NULL,
    [PlannedNumOnProgInstalm]           INT             NULL,
    [PlannedTotalDaysIL]                INT             NULL,
    [ProgStandardStartDate]             DATE            NULL,
    [SmallBusApplicVal]                 DECIMAL (10, 5) NULL,
    [SmallBusEligible]                  BIT             NULL,
    [SmallBusStatusFirstDayStandard]    INT             NULL,
    [SmallBusStatusThreshold]           INT             NULL,
    [SmallBusThresholdDate]             DATE            NULL,
    [YoungAppApplicVal]                 DECIMAL (10, 5) NULL,
    [YoungAppEligible]                  BIT             NULL,
    [YoungAppFirstThresholdDate]        DATE            NULL,
    [YoungAppSecondThresholdDate]       DATE            NULL,
    PRIMARY KEY CLUSTERED ([UKPRN] ASC, [LearnRefNumber] ASC, [AimSeqNumber] ASC)
);

